# Generated by Django 3.1.5 on 2021-12-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_auto_20211212_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_important', '-date']},
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=250),
        ),
    ]
