# Generated by Django 3.1.5 on 2022-01-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_auto_20220105_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPage',
        ),
    ]
