# Generated by Django 3.1.5 on 2022-02-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collections_module', '0001_initial'),
        ('notes', '0023_auto_20220119_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collections_module.collection'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
