# Generated by Django 3.1.5 on 2021-12-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercastomizationmodel',
            name='accent_color',
            field=models.CharField(default='green', max_length=10),
        ),
    ]
