# Generated by Django 3.1.5 on 2022-01-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20211219_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomizationmodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='usercustomizationmodel',
            name='accent_color',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('orange', 'Orange'), ('light_blue', 'Light Blue')], default='Your accent color', max_length=10),
        ),
        migrations.AlterField(
            model_name='usercustomizationmodel',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='Your theme', max_length=5),
        ),
    ]
