# Generated by Django 3.1.5 on 2022-01-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_auto_20220113_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomizationmodel',
            name='accent_color',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('orange', 'Orange'), ('light_blue', 'Light Blue')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='usercustomizationmodel',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5),
        ),
    ]
