# Generated by Django 3.1.5 on 2022-01-22 22:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticate', '0007_auto_20220119_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustomizationModel',
            new_name='UserInfo',
        ),
    ]
